import { Event } from "./types";

export const events: Event[] = [
  {
    id: 1,
    title: "AI Development Best Practices",
    date: "2024-01-19",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Join us for an interactive session on developing responsible and efficient AI systems. We'll cover best practices, ethical considerations, and practical implementation tips.",
    status: "upcoming",
  },
  {
    id: 2,
    title: "Machine Learning Workshop",
    date: "2024-01-12",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "A hands-on workshop focusing on practical machine learning applications. Bring your laptop and get ready to code!",
    status: "past",
  },
  {
    id: 3,
    title: "Introduction to Large Language Models",
    date: "2024-01-05",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "An overview of LLMs, their capabilities, and how to effectively use them in your projects.",
    status: "past",
  },
  {
    id: 4,
    title: "Advanced Natural Language Processing",
    date: "2023-12-29",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Deep dive into NLP techniques and their practical applications in modern AI systems.",
    status: "past",
  },
  {
    id: 5,
    title: "AI Ethics and Responsible Development",
    date: "2023-12-22",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Exploring ethical considerations in AI development and implementing responsible AI practices.",
    status: "past",
  },
  {
    id: 6,
    title: "Generative AI Applications",
    date: "2023-12-15",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Understanding and implementing various generative AI models and their applications.",
    status: "past",
  },
  {
    id: 7,
    title: "AI Model Optimization",
    date: "2023-12-08",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Techniques for optimizing AI models for better performance and efficiency.",
    status: "past",
  },
  {
    id: 8,
    title: "Deep Learning Fundamentals",
    date: "2023-12-01",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Essential concepts and practices in deep learning and neural networks.",
    status: "past",
  },
  {
    id: 9,
    title: "AI for Business Applications",
    date: "2023-11-24",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Implementing AI solutions in business contexts and real-world applications.",
    status: "past",
  },
  {
    id: 10,
    title: "Machine Learning Operations",
    date: "2023-11-17",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Best practices for deploying and maintaining machine learning systems in production.",
    status: "past",
  },
  {
    id: 11,
    title: "Computer Vision Applications",
    date: "2023-11-10",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Exploring computer vision techniques and their practical implementations.",
    status: "past",
  },
  {
    id: 12,
    title: "Reinforcement Learning",
    date: "2023-11-03",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Understanding reinforcement learning algorithms and their applications.",
    status: "past",
  },
  {
    id: 13,
    title: "AI Model Deployment",
    date: "2023-10-27",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Strategies for deploying AI models in production environments.",
    status: "past",
  },
  {
    id: 14,
    title: "Natural Language Understanding",
    date: "2023-10-20",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Advanced techniques in natural language understanding and processing.",
    status: "past",
  },
  {
    id: 15,
    title: "AI System Architecture",
    date: "2023-10-13",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Designing and implementing scalable AI system architectures.",
    status: "past",
  },
  {
    id: 16,
    title: "Transfer Learning in Practice",
    date: "2023-10-06",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Applying transfer learning techniques to improve AI model performance.",
    status: "past",
  },
  {
    id: 17,
    title: "AI Security and Privacy",
    date: "2023-09-29",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Understanding and implementing security measures in AI systems.",
    status: "past",
  },
  {
    id: 18,
    title: "Automated Machine Learning",
    date: "2023-09-22",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Exploring AutoML tools and techniques for efficient model development.",
    status: "past",
  },
  {
    id: 19,
    title: "AI Model Interpretability",
    date: "2023-09-15",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Understanding and implementing techniques for AI model interpretability.",
    status: "past",
  },
  {
    id: 20,
    title: "Edge AI Development",
    date: "2023-09-08",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Developing AI applications for edge devices and mobile platforms.",
    status: "past",
  },
  {
    id: 21,
    title: "AI Testing and Quality Assurance",
    date: "2023-09-01",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Best practices for testing and ensuring quality in AI systems.",
    status: "past",
  },
  {
    id: 22,
    title: "Federated Learning",
    date: "2023-08-25",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Understanding and implementing federated learning techniques.",
    status: "past",
  },
  {
    id: 23,
    title: "AI Model Monitoring",
    date: "2023-08-18",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Implementing effective monitoring systems for AI models in production.",
    status: "past",
  },
  {
    id: 24,
    title: "Graph Neural Networks",
    date: "2023-08-11",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Exploring graph neural networks and their applications.",
    status: "past",
  },
  {
    id: 25,
    title: "AI Ethics in Practice",
    date: "2023-08-04",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Implementing ethical AI practices in real-world applications.",
    status: "past",
  },
  {
    id: 26,
    title: "Quantum Machine Learning",
    date: "2023-07-28",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Introduction to quantum computing concepts in machine learning.",
    status: "past",
  },
  {
    id: 27,
    title: "AI Infrastructure Design",
    date: "2023-07-21",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Designing and implementing robust AI infrastructure.",
    status: "past",
  },
  {
    id: 28,
    title: "Advanced Deep Learning",
    date: "2023-07-14",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Advanced techniques and architectures in deep learning.",
    status: "past",
  },
  {
    id: 29,
    title: "AI Project Management",
    date: "2023-07-07",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Best practices for managing AI development projects.",
    status: "past",
  },
  {
    id: 30,
    title: "MLOps Fundamentals",
    date: "2023-06-30",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Introduction to MLOps principles and practices.",
    status: "past",
  },
  {
    id: 31,
    title: "AI Model Scaling",
    date: "2023-06-23",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Techniques for scaling AI models effectively.",
    status: "past",
  },
  {
    id: 32,
    title: "Getting Started with AI Development",
    date: "2023-06-16",
    time: "12:00 PM EDT",
    location: "Virtual Meeting",
    description: "Introduction to AI development fundamentals and best practices.",
    status: "past",
  },
];