// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ouaycpbocopnajwdrmkv.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91YXljcGJvY29wbmFqd2RybWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIxMjcxMzUsImV4cCI6MjA0NzcwMzEzNX0.9lH-PmnxNAtNNiIhf9jzgPyzfFJlbljIzlR7fHFvjmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);